# Generated by Django 6.0.6 on 2026-07-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('kg', 'Кыргызча')], default='ru', max_length=2, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(help_text='Например: Абонементы, Расписание, Бассейн', max_length=100, verbose_name='Название категории ru')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название категории en')),
                ('name_kg', models.CharField(blank=True, max_length=100, verbose_name='Название категории kg')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать в боте')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше категория в списке.', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория FAQ',
                'verbose_name_plural': 'FAQ · Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=255, verbose_name='Вопрос ru')),
                ('question_en', models.CharField(blank=True, max_length=255, verbose_name='Вопрос en')),
                ('question_kg', models.CharField(blank=True, max_length=255, verbose_name='Вопрос kg')),
                ('answer_ru', models.TextField(verbose_name='Ответ ru')),
                ('answer_en', models.TextField(blank=True, verbose_name='Ответ en')),
                ('answer_kg', models.TextField(blank=True, verbose_name='Ответ kg')),
                ('is_published', models.BooleanField(default=True, verbose_name='Показывать в боте')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше вопрос в списке.', verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot_app.faqcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'FAQ · Вопросы и ответы',
                'ordering': ['order'],
            },
        ),
    ]
